version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=yt_transcription.settings

# command: python manage.py runserver 0.0.0.0:8000
